import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Share/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ali Ashraf",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mx-w-[1280px] w-[1200px] mx-auto border-2 border-white bg-black">
        {children}
        <Navbar></Navbar>
      </body>
    </html>
  );
}
